version: "3.8"

services:
  app:
    build: ../. 
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - BDmysql
    ports:
      - "3000:3000"
    command: npx nodemon ./src/bin/www.js

  BDmysql:
    image: mysql
    